alias ll='ls -l'
alias tailf='tail -f'

#
# GIT
#
alias gc="git commit -m $1"
alias gca="git add -A; git commit -m $1"
alias gs='git status'
alias gl='git log'
alias gf='git fetch'
alias gch='git checkout'
alias gb='git branch'
alias gst='git stash'
alias gm='git merge'
alias gp='git push'
alias gpl='git pull'
alias gpom="git pull origin master"

# DOS2UNIX
alias dos2unix="python -c \"import sys; import fileinput; sys.stdout.writelines(line.replace('\r', '\n') for line in fileinput.input(mode='rU'))\""

ulimit -n 4096

export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad

# Set Clang as the default compiler for the system
#export CC=clang
#export CFLAGS=-Qunused-arguments
#export CPPFLAGS=-Qunused-arguments

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # This loads RVM into a shell session.
PATH=$PATH:$HOME/.rvm/bin

export PATH=/usr/local/bin:/usr/local/sbin:/Users/smarques/.rvm/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/X11/bin:/usr/local/share/npm/bin
