set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'vim-ruby/vim-ruby'
Bundle 'pix/vim-align'
Bundle 'oscarh/vimerl'
Bundle 'tpope/vim-fugitive'
Bundle 'tomtom/tcomment_vim'
Bundle 'nanotech/jellybeans.vim'
Bundle 'dsawardekar/ember.vim'
Bundle 'derekwyatt/vim-scala'
Bundle 'thoughtbot/vim-rspec'
Bundle 'tpope/vim-dispatch'
Bundle 'bling/vim-airline'
Bundle 'kien/ctrlp.vim'
Bundle 'jlanzarotta/bufexplorer'
Bundle 'scrooloose/nerdtree'
Bundle 'tpope/vim-rails'
Bundle 'gcmt/wildfire.vim'
Bundle 'bkad/CamelCaseMotion'
Bundle 'edkolev/tmuxline.vim'
Bundle 'rstacruz/sparkup'
Bundle 'rking/ag.vim'
Bundle 'scrooloose/syntastic'
Bundle 'airblade/vim-gitgutter'
Bundle 'tpope/vim-rake'
" Bundle 'suan/vim-instant-markdown'

colorscheme jellybeans

syntax on
set nocp
set guifont=Monaco:h12
set number

set nobackup
set nowritebackup
set noswapfile
set autoread
set hlsearch

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

set laststatus=2
set t_Co=256

set wildmode=list:longest

if has("gui_running")
	set guioptions=egmrLt
else
  set background=dark
endif

filetype plugin indent on

autocmd BufWritePre * :%s/\s\+$//e

let g:rspec_command = "Dispatch rspec {spec}"

" RSpec.vim mappings
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>

" Builds tags for current directory
nmap <F2> :!/usr/local/Cellar/ctags/5.8/bin/ctags -R .<CR>

" Clears CtrlP cache
nmap <F3> :CtrlPClearCache<CR>

" Changing tabs
nmap <Tab> :tabn<CR>
nmap <S-Tab> :tabp<CR>

"Ctags search always lists all occurrences
nmap <C-]> g<C-]>

" Airline settings
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
" let g:airline_theme='badwolf'

" CtrlP settings
" let g:ctrlp_cmd = 'CtrlPMRU'
