set nocompatible               " be iMproved
filetype off                   " required!

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'gmarik/vundle'
Bundle 'vim-ruby/vim-ruby'
Bundle 'pix/vim-align'
Bundle 'oscarh/vimerl'
Bundle 'tpope/vim-fugitive'
Bundle 'tomtom/tcomment_vim'
Bundle 'nanotech/jellybeans.vim'
Bundle 'dsawardekar/ember.vim'
Bundle 'derekwyatt/vim-scala'
Bundle 'thoughtbot/vim-rspec'
Bundle 'tpope/vim-dispatch'
Bundle 'bling/vim-airline'
Bundle 'kien/ctrlp.vim'

colorscheme jellybeans

syntax on
set nocp
set guifont=Monaco:h12
set number

set nobackup
set nowritebackup
set noswapfile
set autoread
set hlsearch

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

if has("gui_running")
	set guioptions=egmrLt
else
  set background=dark
endif

filetype plugin indent on

autocmd BufWritePre * :%s/\s\+$//e

let g:rspec_command = "Dispatch rspec {spec}"

" RSpec.vim mappings
map <Leader>t :call RunCurrentSpecFile()<CR>
map <Leader>s :call RunNearestSpec()<CR>
map <Leader>l :call RunLastSpec()<CR>
map <Leader>a :call RunAllSpecs()<CR>
